network:
  name: resnet50

  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  fine_tune_from: None

  projection_head:
    mlp_hidden_size: 4096
    projection_size: 256

data_transforms:
  s: 1
  input_shape: (224,224,3)

trainer:
  batch_size: 1024
  m: 0.996 # momentum update
  max_epochs: 200
  num_workers: 8
  warmup_epochs: 10

optimizer:
  params:
    lr: 0.2
    momentum: 0.9
    weight_decay: 0.0000015